all:
	make -C DataHolder
	make -C Input
	make -C Layer
	make -C Model
	make -C Tutors
	make -C ReLU
	make -C Wire
	make -C Reshape
	make -C SoftMax
	make -C Generator
	make -C Tensor2JPEG
	make -C Gain
	make -C Arctan
	make -C ReLUx
	make -C ELU
	make -C SELU
	make -C Dropout
	make -C SkipConnections
run:
	clear
	make -C DataHolder run
	make -C Input run
	make -C Layer run
	make -C Model run
	make -C Tutors run
	make -C ReLU run
	make -C Wire run
	make -C Reshape run
	make -C SoftMax run
	make -C Generator run
	make -C Tensor2JPEG run
	make -C Gain run
	make -C Arctan run
	make -C ReLUx run
	make -C ELU run
	make -C SELU run
	make -C Dropout run
	make -C SkipConnections run
	echo 'Тестирование удачно завершено!'
clean:
	make -C DataHolder clean
	make -C Input clean
	make -C Layer clean
	make -C Model clean
	make -C Tutors clean
	make -C ReLU clean
	make -C Wire clean
	make -C Reshape clean
	make -C SoftMax clean
	make -C Generator clean
	make -C Tensor2JPEG clean
	make -C Gain clean
	make -C Arctan clean
	make -C ReLUx clean
	make -C ELU clean
	make -C SELU clean
	make -C Dropout clean
	make -C SkipConnections clean
