all:
	make -C DataHolder
	make -C Input
	make -C Layer
	make -C Model
	make -C ReLU
	make -C Wire
run:
	clear
	make -C DataHolder run
	make -C Input run
	make -C Layer run
	make -C Model run
	make -C ReLU run
	make -C Wire run
	echo 'Тестирование удачно завершено!'
clean:
	make -C DataHolder clean
	make -C Input clean
	make -C Layer clean
	make -C Model clean
	make -C ReLU clean
	make -C Wire clean
