all:
	make -C DataHolder
	make -C Input
	make -C Layer
	make -C Model
	make -C ReLU
	make -C Wire
	make -C Reshape
	make -C SoftMax
	make -C Generator
run:
	clear
	make -C DataHolder run
	make -C Input run
	make -C Layer run
	make -C Model run
	make -C ReLU run
	make -C Wire run
	make -C Reshape run
	make -C SoftMax run
	make -C Generator run
	echo 'Тестирование удачно завершено!'
clean:
	make -C DataHolder clean
	make -C Input clean
	make -C Layer clean
	make -C Model clean
	make -C ReLU clean
	make -C Wire clean
	make -C Reshape clean
	make -C SoftMax clean
	make -C Generator clean

